export const USER_SIGNIN_API_JIRACLONE = 'USER_SIGNIN_API_JIRACLONE';


export const USLOGIN = 'USLOGIN';


//GET ALL PROJECT 
export const GET_ALL_PROJECT_CATEGORY_SAGA = 'GET_ALL_PROJECT_CATEGORY_SAGA';
export const GET_ALL_PROJECT_CATEGORY = 'GET_ALL_PROJECT_CATEGORY';

//CREATE PROJECT
export const CREATE_PROJECT_CATEGORY_SAGA = 'CREATE_PROJECT_CATEGORY_SAGA';
export const CREATE_PROJECT_CATEGORY = 'CREATE_PROJECT_CATEGORY';

//GET LIST PROJECT
export const GET_LIST_PROJECT_SAGA = 'GET_LIST_PROJECT_SAGA';
export const GET_LIST_PROJECT = 'GET_LIST_PROJECT';

//UPDATE PROJECT
export const UPDATE_PROJECT_SAGA = 'UPDATE_PROJECT_SAGA';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';


//delete PROJECT
export const DELETE_PROJECT_SAGA = 'DELETE_PROJECT_SAGA';
export const DELETE_PROJECT = 'DELETE_PROJECT';

//GET USER 
export const GET_USER_SAGA = 'GET_USER_SAGA';
export const GET_USER = 'GET_USER';


//add  USER 
export const ADD_USER_SAGA = 'ADD_USER_SAGA';
export const ADD_USER = 'ADD_USER';

//remove  USER from project
export const REMOVE_USER_FROM_PROJECT_SAGA = 'REMOVE_USER_FROM_PROJECT_SAGA';


//GET  PROJECT DETAILS
export const GET_PROJECT_DETAILS_SAGA = 'GET_PROJECT_DETAILS_SAGA';


//GET ALL PROJECT FORM
export const GET_ALLPROJECT_CREATE_SAGA = 'GET_ALLPROJECT_CREATE_SAGA';
export const GET_ALLPROJECT_CREATE = 'GET_ALLPROJECT_CREATE';

//TASK TYPE
export const GET_ALL_TASK_TYPE_SAGA = 'GET_ALL_TASK_TYPE_SAGA';
export const GET_ALL_TASK_TYPE = 'GET_ALL_TASK_TYPE';

//TASK TYPE
export const CREATE_TASK_SAGA = 'CREATE_TASK_SAGA';
export const CREATE_TASK = 'CREATE_TASK';

//TASK 
export const GET_TASK_DETAIL_SAGA = 'GET_TASK_DETAIL_SAGA';
export const GET_TASK_DETAIL = 'GET_TASK_DETAIL';
export const CHANGE_TASK_MODAL = 'CHANGE_TASK_MODAL';

//PRIORITY
export const GET_ALL_PRIORITY_SAGA = 'GET_ALL_PRIORITY_SAGA';
export const GET_ALL_PRIORITY = 'GET_ALL_PRIORITY';


//STATUS
export const GET_STATUS_SAGA = 'GET_STATUS_SAGA';
export const GET_STATUS = 'GET_STATUS';

export const GET_USER_BY_ID = 'GET_USER_BY_ID';


export const UPDATE_STATUS_TASK_SAGA = 'UPDATE_STATUS_TASK_SAGA';
export const REMOVE_TASK_SAGA = 'REMOVE_TASK_SAGA';

export const HANDLE_CHANGE_POST_API_UPDATE_TASK_SAGA = 'HANDLE_CHANGE_POST_API_UPDATE_TASK_SAGA';

export const ADD_ASSIGNESS = 'ADD_ASSIGNESS';
export const REMOVE_ASSIGNESS = 'REMOVE_ASSIGNESS';

//COMMENT
export const GET_COMMENT_SAGA = 'GET_COMMENT_SAGA';
export const GET_COMMENT = 'GET_COMMENT';

export const INSERT_COMMENT_SAGA = 'INSERT_COMMENT_SAGA';

export const UPDATE_COMMENT_SAGA = 'UPDATE_COMMENT_SAGA';
export const DELETED_COMMENT_SAGA = 'DELETED_COMMENT_SAGA';

export const SIGN_UP_SAGA = 'SIGN_UP_SAGA';

export const GET_LIST_USER = 'GET_LIST_USER';
export const GET_LIST_USER_SAGA = 'GET_LIST_USER_SAGA';

export const EDIT_USER_SAGA = 'EDIT_USER_SAGA';

export const DELETE_USER_SAGA = 'DELETE_USER_SAGA';

export const LOGOUT_SAGA = 'LOGOUT_SAGA';

